// Shared API types. These are DERIVED from the backend's OpenAPI spec (HTS-050): the types come
// from `./schema.d.ts`, generated by `npm run gen:api` from /v3/api-docs. Deriving them here means
// the SPA can never silently drift from the backend contract — if a field is added, removed, or
// retyped on the server, regenerating the schema makes `npm run typecheck` fail until the frontend
// is updated to match (architecture.md §8 / HTS-031).

import type { components } from './schema';

/** A single field-level validation error (architecture.md §8). */
export type FieldError = components['schemas']['FieldError'];

/** Standardized error body returned by the backend for every 4xx/5xx (architecture.md §8). */
export type ApiErrorBody = components['schemas']['ApiError'];

/** Health probe response ({@code {"status":"UP"}}). */
export type HealthStatus = components['schemas']['HealthStatus'];

/** Public view of a user returned by signup / GET me (mirrors backend UserResponse). */
export type UserResponse = components['schemas']['UserResponse'];
