-- Ticket activity history (HTS-041, EP-09 stretch — architecture.md §6). Append-only audit log:
-- one row per changed field on create/edit and per state transition, written in the same
-- transaction as the mutation. Rows are never updated or deleted (there is no edit/delete path);
-- they cascade away with their ticket. old/new values are stored as human-readable strings captured
-- at the time of the change, so the log stays accurate even if a referenced team/epic is later
-- renamed or removed.
--
-- `seq` is a DB-assigned monotonic identity used purely for ordering: several rows from one
-- multi-field edit share the same occurred_at (and a UUIDv7 id is only millisecond-ordered, so it
-- cannot tie-break within a millisecond). seq is assigned in insert order, giving a stable
-- chronological sort for the history view.
CREATE TABLE ticket_activity (
    id          UUID PRIMARY KEY,
    seq         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ticket_id   UUID NOT NULL REFERENCES tickets (id) ON DELETE CASCADE,
    actor_email VARCHAR(320) NOT NULL,
    field       VARCHAR(30) NOT NULL,
    old_value   TEXT,
    new_value   TEXT,
    occurred_at TIMESTAMPTZ NOT NULL
);

-- The history view lists a single ticket's activity in insertion (chronological) order.
CREATE INDEX ix_ticket_activity_ticket ON ticket_activity (ticket_id, seq);
